"""Predefined evidence extraction templates."""

EVIDENCE_TEMPLATES = {
    "clinical_trial": [
        "study_design",
        "population",
        "sample_size",
        "intervention",
        "dose",
        "duration",
        "comparator",
        "primary_outcome",
        "secondary_outcomes",
        "adverse_events",
        "main_findings",
        "limitations",
        "funding",
        "conflict_of_interest",
        "registration_number",
    ],
    
    "observational_study": [
        "study_design",
        "population",
        "sample_size",
        "exposure",
        "outcome",
        "confounders",
        "statistical_methods",
        "main_findings",
        "limitations",
        "funding",
    ],
    
    "systematic_review": [
        "research_question",
        "databases_searched",
        "search_date",
        "inclusion_criteria",
        "exclusion_criteria",
        "number_of_studies_included",
        "quality_assessment",
        "synthesis_method",
        "main_findings",
        "heterogeneity",
        "publication_bias",
        "limitations",
        "funding",
    ],
    
    "in_vitro_study": [
        "compound_extract",
        "concentration",
        "assay_type",
        "cell_line_organism",
        "incubation_time",
        "positive_control",
        "negative_control",
        "replicates",
        "results",
        "statistical_analysis",
        "limitations",
    ],
    
    "extraction_study": [
        "plant_material",
        "extraction_method",
        "solvent",
        "temperature",
        "time",
        "yield",
        "phytochemical_analysis",
        "compounds_identified",
        "quantification_method",
        "limitations",
    ],
    
    "antimicrobial_study": [
        "organism_tested",
        "strain",
        "extract_compound",
        "concentration_range",
        "assay_method",
        "incubation_conditions",
        "positive_control",
        "mic_value",
        "mbc_value",
        "zone_of_inhibition",
        "mechanism",
        "limitations",
    ],
    
    "general": [
        "study_design",
        "population_sample",
        "methods",
        "key_findings",
        "limitations",
        "conclusions",
        "funding",
    ],
}